---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: document
  path: index.html
  label: Home
  templates:
  - settings
  - type: directory
  path: about.html
  label: About
  create: all
  match: "**/[!index]*"
  templates:
  - about
- type: directory
  path: contact.html
  label: Contact
  create: all
  match: "**/*"
  templates:
  - contact
  - type: directory
  path: bookdetails.html
  label: bookdetails
  create: all
  match: "**/*"
  templates:
  - bookdetails
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ladytraceywebsite/
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
